 server {

        listen       80;
        listen       443 ssl;

    server_name greenpasschecker.TLD www.greenpasschecker.TLD;
        ssl_certificate  /etc/nginx/ssl/greenpasschecker/certificate.pem;
  ssl_certificate_key /etc/nginx/ssl/greenpasschecker/privatekey.pem;

access_log /var/log/nginx/greenpasschecker.access.log;
            error_log /var/log/nginx/greenpasschecker.error.log;
    location / {
        proxy_pass http://localhost:3000;
        include proxy_params;
    }
}
